In [4]:
import pandas as pd

data = pd.Series([10, 20, 30, 40, 50])
print(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
third_element = data[2]
print(third_element)

30

In [6]:
print(data.dtype)

int64

In [8]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [11]:
age_column = df['Age']
print(age_column)

0    25
1    30
2    35
Name: Age, dtype: int64

In [12]:
print(df.shape)

(3, 2)

In [19]:
df.loc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [25]:
age = df.iloc[0, 1]
print(age)

25

In [26]:
import pandas as pd
df = pd.read_csv('president_heights.csv')
print(df.head())

   order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [27]:
import pandas as pd

df = pd.read_csv('president_heights.csv')
average_height = df['height(cm)'].mean() 
print(average_height)

179.93023255813952

In [28]:
tallest = df.loc[df['height(cm)'].idxmax(), 'name']
print(tallest)

Abraham Lincoln

In [31]:
import pandas as pd
import numpy as np

np.random.seed(42)  # reproducibility ke liye
df = pd.DataFrame(np.random.rand(5, 3), columns=['A', 'B', 'C'])
df

          A         B         C
0  0.374540  0.950714  0.731994
1  0.598658  0.156019  0.155995
2  0.058084  0.866176  0.601115
3  0.708073  0.020584  0.969910
4  0.832443  0.212339  0.181825

In [32]:
column_means = df.mean()
print(column_means)

A    0.514359
B    0.441167
C    0.528168
dtype: float64